---
title: "graphic test"
author: "Kota Mori"
date: "July 17, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(gogamer)
```

Default size is 5
```{r, fig.width=5, fig.height=5}
plotat(saikoyo, 116)
ggplot2::ggsave("output/test.pdf", width = 5, height = 5)
ggplot2::ggsave("output/test.png", width = 5, height = 5)
```

If fig.width and fig.height change, stone sizes are no good
```{r, fig.width=2, fig.height=2}
plotat(saikoyo, 116)
```

```{r, fig.width=8, fig.height=8}
plotat(saikoyo, 116)
```


Use 'targetwidth' option to adjust the size
```{r, fig.width=2, fig.height=2}
plotat(saikoyo, 116, targetwidth = 2)
```

```{r, fig.width=8, fig.height=8}
plotat(saikoyo, 116, targetwidth = 8)
```


More extreme cases
```{r, fig.width=1, fig.height=1}
plotat(saikoyo, 116, targetwidth = 1)
```

```{r, fig.width=20, fig.height=20}
plotat(saikoyo, 116, targetwidth = 20)
```


```{r, fig.width=5, fig.height=0.6}
gogamer:::kifunote(kifu(mimiaka))
```


```{r, fig.width=5, fig.height=1.4}
x <- read_sgf("../tests/sample/ko.sgf")
print(x)
gogamer:::kifunote(kifu(x, 1, 108))
```


```{r, fig.width=5, fig.height=6.37}
plot(kifu(x, 1, 108))
```

```{r, fig.width=5, fig.height=6.37}
invisible(plot(kifu(x, 1, 108)))
```

```{r, fig.width=5, fig.height=5.6}
g <- plot(kifu(mimiaka))
suggested_size(g)
g
```

```{r, fig.width=7, fig.height=7.84}
g <- plot(kifu(mimiaka), targetwidth = 7)
suggested_size(g)
g
```


```{r, fig.width=5, fig.height=5.96}
y <- read_sgf("../tests/sample/ko9.sgf")
print(y)
plotat(y, 80)
plot(kifu(y))
```

```{r, fig.width=5, fig.height=6.5}
plot(kifu(y), adjustsizeonnote = TRUE, moveperrow = 4)
```


When label is not added
```{r, fig.width=5, fig.height=5}
plotat(saikoyo, 116, targetwidth = 5, axislabels = TRUE)
plotat(saikoyo, 116, targetwidth = 5, axislabels = FALSE)
plotat(y, 100, targetwidth = 5, axislabels = TRUE)
plotat(y, 100, targetwidth = 5, axislabels = FALSE)
library(magrittr)
ggoban(11, axislabels = FALSE) %>% addstones(1, 1, 1, boardsize = 11)
ggoban(13, axislabels = FALSE) %>% addstones(1, 1, 1, boardsize = 13)
ggoban(19, axislabels = FALSE) %>% addstones(1, 1, 1, boardsize = 19)
```

```{r, fig.width=8, fig.height=8}
plotat(saikoyo, 116, targetwidth = 8, axislabels = TRUE)
plotat(saikoyo, 116, targetwidth = 8, axislabels = FALSE)
plotat(y, 100, targetwidth = 8, axislabels = TRUE)
plotat(y, 100, targetwidth = 8, axislabels = FALSE)
```

