// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prune_sgf
std::string prune_sgf(std::string sgf, bool keep_first);
RcppExport SEXP sgf_prune_sgf(SEXP sgfSEXP, SEXP keep_firstSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type sgf(sgfSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_first(keep_firstSEXP);
    __result = Rcpp::wrap(prune_sgf(sgf, keep_first));
    return __result;
END_RCPP
}
