# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove branches from SGF text
#' @param sgf  Scalar character formatted as SGF
#' @param keep_first  Logical. If TRUE, keep the first branch.
#'   Otherwise, keep the last branch.
#' @return Scalar character of SGF text where branches are removed
#' @export
prune_sgf <- function(sgf, keep_first = TRUE) {
    .Call('sgf_prune_sgf', PACKAGE = 'sgf', sgf, keep_first)
}

