# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_movenumber <- function(hasmove, children, onebased = TRUE) {
    .Call('gogamer_get_movenumber', PACKAGE = 'gogamer', hasmove, children, onebased)
}

#' Remove branches from SGF text
#' @param sgf  Scalar character formatted as SGF
#' @param keepfirst  Logical. If TRUE, keep the first branch.
#'   Otherwise, keep the last branch.
#' @return Scalar character of SGF text where branches are removed
#' @export
prune_sgf <- function(sgf, keepfirst = TRUE) {
    .Call('gogamer_prune_sgf', PACKAGE = 'gogamer', sgf, keepfirst)
}

sgftree_test <- function(sgf) {
    invisible(.Call('gogamer_sgftree_test', PACKAGE = 'gogamer', sgf))
}

make_sgftree <- function(sgf, bynode = TRUE) {
    .Call('gogamer_make_sgftree', PACKAGE = 'gogamer', sgf, bynode)
}

#' Obtains the transition of board configuration
#' @param boardsize integer of the board size
#' @param ismove_vec logical vector indicating moves, as opposed to setup
#' @param x_vec integer vector of x coordinate (horizontal)
#' @param y_vec integer vector of y coordinate (vertical)
#' @param color_vec integer vector of color vector
#' @return \code{data.frame}
#' @keywords internal
get_transitions <- function(boardsize, ismove_vec, x_vec, y_vec, color_vec) {
    .Call('gogamer_get_transitions', PACKAGE = 'gogamer', boardsize, ismove_vec, x_vec, y_vec, color_vec)
}

#' Obtains the transition of board configuration
#' @param data   A list of data.frames, each contains
#' @keywords internal
get_transitiontree <- function(data, children, boardsize) {
    .Call('gogamer_get_transitiontree', PACKAGE = 'gogamer', data, children, boardsize)
}

tree_compressor <- function(children, onebased = TRUE) {
    .Call('gogamer_tree_compressor', PACKAGE = 'gogamer', children, onebased)
}

